export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const DISPLAYED_ON_PROFILE = 'DISPLAYED_ON_PROFILE';
export const GET_RANDOM_RECIPE = 'GET_RANDOM_RECIPE';
export const RESET_REDIRECT = 'RESET_REDIRECT';

export const CREATE_RECIPE_SUCCESS = 'CREATE_RECIPE_SUCCESS';
export const CREATE_RECIPE_FAIL = 'CREATE_RECIPE_FAIL';
export const LOAD_RECIPE = 'LOAD_RECIPE';
export const LOAD_RECIPE_FAIL = 'LOAD_RECIPE_FAIL';
export const ADD_RECIPE_REVIEW = 'ADD_RECIPE_REVIEW';
export const REDIRECT_TO_RECIPE = 'REDIRECT_TO_RECIPE';
export const SET_LOADING = 'SET_LOADING';
export const STOP_LOADING = 'STOP_LOADING';
export const USER_SAVE_RECIPE = 'USER_SAVE_RECIPE';
export const USER_UNSAVE_RECIPE = 'USER_UNSAVE_RECIPE';

export const GET_ALL_RECIPES = 'GET_ALL_RECIPES';
export const GET_RECIPE_BY_TYPE = 'GET_RECIPE_BY_TYPE';
export const SET_QUERY_VALUE = 'SET_QUERY_VALUE';
export const GET_SEARCH_QUERY_RESULT = 'GET_SEARCH_QUERY_RESULT';
